//package br.ufc.dc.validc.model;
//
//import java.time.LocalDateTime;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//
//@DynamoDBTable(tableName = "hashfile")
//public class InfoValidation {
//
//	private String id;
//	private String createdAt;
//	private String motivo;
//	private boolean isValid;
//	private String filename;
//	private String username;
//
//	public InfoValidation() {
//	}
//
//	public InfoValidation(LocalDateTime createdAt, String motivo, boolean isValid, String filename, String username) {
//		super();
//		this.createdAt = createdAt.toString();
//		this.motivo = motivo;
//		this.isValid = isValid;
//		this.filename = filename;
//		this.username = username;
//	}
//
//	@DynamoDBHashKey
//	@DynamoDBAutoGeneratedKey
//	public String getId() {
//		return id;
//	}
//
//	public void setId(String id) {
//		this.id = id;
//	}
//
//	@DynamoDBAttribute
//	public String getCreatedAt() {
//		return createdAt.toString();
//	}
//
//	public void setCreatedAt(LocalDateTime createdAt) {
//		this.createdAt = createdAt.toString();
//	}
//	
//	public void setCreatedAt(String createdAt) {
//		this.createdAt = createdAt;
//	}
//	
//
//	@DynamoDBAttribute
//	public String getMotivo() {
//		return motivo;
//	}
//
//	public void setMotivo(String motivo) {
//		this.motivo = motivo;
//	}
//
//	@DynamoDBAttribute
//	public boolean getIsValid() {
//		return isValid;
//	}
//
//	public void setIsValid(boolean isValid) {
//		this.isValid = isValid;
//	}
//
//	@DynamoDBAttribute
//	public String getFilename() {
//		return filename;
//	}
//
//	public void setFilename(String filename) {
//		this.filename = filename;
//	}
//
//	@DynamoDBAttribute
//	public String getUsername() {
//		return username;
//	}
//
//	public void setUsername(String username) {
//		this.username = username;
//	}
//
//	@Override
//	public String toString() {
//		return "InfoValidation [id=" + id + ", createdAt=" + createdAt + ", motivo=" + motivo + ", isValid=" + isValid
//				+ ", filename=" + filename + ", username=" + username + "]";
//	}
//
//	
//}
