runtime: java11
instance_class: F2
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"

#instance_class: F4
#env_variables:
#  SPRING_PROFILES_ACTIVE: "prod"
#entrypoint: java -noverify -jar validc-0.0.1-SNAPSHOT.jar
#handlers:
#- url: /.*
#  script: auto
#  http_headers:
#    Access-Control-Allow-Origin: *
